// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanUp(arg1:string):Promise<void>;

export function CompressPlaydateOS():Promise<void>;

export function DownloadOS(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DownloadPlaydateOS(arg1:string):Promise<void>;

export function ExtractOS(arg1:string,arg2:string):Promise<void>;

export function ExtractPlaydateOS(arg1:boolean):Promise<void>;

export function FinishRegistration(arg1:string):Promise<Record<string, any>>;

export function GetPin(arg1:string):Promise<Record<string, any>>;

export function GetSerialPorts():Promise<Array<string>>;

export function InstallPatchedPlaydateOS(arg1:string):Promise<void>;

export function UploadPatchedPlaydateOS(arg1:string):Promise<void>;
