// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFunnyLoader() {
  return window['go']['main']['App']['DownloadFunnyLoader']();
}

export function DownloadFunnyOS() {
  return window['go']['main']['App']['DownloadFunnyOS']();
}

export function DownloadIndexOS() {
  return window['go']['main']['App']['DownloadIndexOS']();
}

export function DownloadOS(arg1) {
  return window['go']['main']['App']['DownloadOS'](arg1);
}

export function DownloadYapOS() {
  return window['go']['main']['App']['DownloadYapOS']();
}

export function ExtractPlaydateOS() {
  return window['go']['main']['App']['ExtractPlaydateOS']();
}

export function FinishRegistration(arg1) {
  return window['go']['main']['App']['FinishRegistration'](arg1);
}

export function GetPin(arg1) {
  return window['go']['main']['App']['GetPin'](arg1);
}
