// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFunnyLoader():Promise<void>;

export function DownloadFunnyOS():Promise<void>;

export function DownloadIndexOS():Promise<void>;

export function DownloadOS(arg1:string):Promise<void>;

export function DownloadYapOS():Promise<void>;

export function FinishRegistration(arg1:string):Promise<Record<string, any>>;

export function GetPin(arg1:string):Promise<Record<string, any>>;
