// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishRegistration(arg1:string):Promise<Record<string, any>>;

export function GetPin(arg1:string):Promise<Record<string, any>>;
