// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadOS(arg1) {
  return window['go']['main']['App']['DownloadOS'](arg1);
}

export function FinishRegistration(arg1) {
  return window['go']['main']['App']['FinishRegistration'](arg1);
}

export function GetPin(arg1) {
  return window['go']['main']['App']['GetPin'](arg1);
}
