// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressPlaydateOS() {
  return window['go']['main']['App']['CompressPlaydateOS']();
}

export function DownloadOS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadOS'](arg1, arg2, arg3, arg4);
}

export function DownloadPlaydateOS(arg1) {
  return window['go']['main']['App']['DownloadPlaydateOS'](arg1);
}

export function ExtractOS(arg1, arg2) {
  return window['go']['main']['App']['ExtractOS'](arg1, arg2);
}

export function ExtractPlaydateOS(arg1) {
  return window['go']['main']['App']['ExtractPlaydateOS'](arg1);
}

export function FinishRegistration(arg1) {
  return window['go']['main']['App']['FinishRegistration'](arg1);
}

export function GetPin(arg1) {
  return window['go']['main']['App']['GetPin'](arg1);
}
